export enum SwaggerTag {
	USER = 'User',
	UPLOAD = 'Upload',
	ORDER = 'Order',
	AUTHENTICATION = 'Authentication',
	CART = 'Cart',
	CHECKOUT = 'Checkout',
	PAYMENT = 'Payment',
	EXPO = 'Expo',
	FEEDBACK = 'Feedback',
	RECIPE = 'Recipe',
	CATEGORY = 'Category',
	FOODSTYLE = 'Foodstyle',
	INGREDIENT = 'Ingredient',
	MEALKIT = 'Mealkit',
	ACCOUNT = 'Account',
	UNIT = 'Unit',
	NUTRITION = 'Nutrition',
	BATCH = 'Batch',
	ADMIN = 'Admin',
	MODERATOR = 'Moderator',
	SHIPPER = 'Shipper'
}
